services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: notes_db
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/notes_db
    depends_on:
      - db
    volumes:
      - ./static:/app/static
      - ./data:/app/data
